#!/usr/bin/env php
<?php

// phpunit PHP file can be "included" as it contains declare(strict_types=1)
// line which must be the first executed line in a script. So it is called
// in a child process
passthru(PHP_BINARY . ' vendor/phpunit/phpunit/phpunit');
